# Generated by Django 3.1.4 on 2020-12-27 17:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201226_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated',
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.CharField(choices=[('1', 'least'), ('2', 'less_than_average'), ('3', 'average'), ('4', 'more_than_average'), ('5', 'most')], default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.survey'),
            preserve_default=False,
        ),
    ]
