# Generated by Django 3.1.4 on 2020-12-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20201227_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
